name: Deploy to production
on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./docker/web/Dockerfile
            image: ghcr.io/${{ github.repository }}web
          - dockerfile: ./docker/worker/Dockerfile
            image: ghcr.io/${{ github.repository }}worker
    uses: ./.github/workflows/build_docker.yml
    with:
      image: ${{ matrix.image }}
      dockerfile: ${{ matrix.dockerfile }}

  deploy-api:
    needs: [build]
    uses: ./.github/workflows/deployment.yml
    with:
      versionvar_filename: keeshond
      service_name: analytics-api
      env_name: prod-eu-west
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  deploy-worker:
    needs: [build, deploy-api]
    uses: ./.github/workflows/deployment.yml
    with:
      versionvar_filename: keeshond
      service_name: analytics-worker
      env_name: prod-eu-west
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  deploy-api-test:
    needs: [build]
    uses: ./.github/workflows/deployment.yml
    with:
      versionvar_filename: keeshond
      service_name: analytics-api
      env_name: test
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}